# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11eVnATPl-wExPIPg0xClGECtXXZQC96a
"""

!pip install pytesseract
!pip install pillow
!sudo apt install tesseract-ocr
import pytesseract
from PIL import Image
from gtts import gTTS
import os

# OCR motorini o'rnatish yo'li (o'z tizimingizga moslash)
pytesseract.pytesseract.tesseract_cmd = r'/usr/bin/tesseract'  # Tesseract yo'lini o'zingizga moslang

# Rasmni ochish
rasm = Image.open('matin.jpg')

# Rasmdagi matnni chiqarish
matn = pytesseract.image_to_string(rasm)
print("Rasmdagi matn:")
print(matn)
# Matnni belgilash
text = matn

# Ovoz yaratish (gTTS - Google Text-to-Speech)
language = 'en'  # Changed to English ('en')
tts = gTTS(text=text, lang=language, slow=False)

# Ovoz faylini saqlash
audio_file = "output1.mp3"
tts.save(audio_file)


# Ovoz faylini tinglash (Google Colab-da)
from IPython.display import Audio
Audio(audio_file)